workflows:
  ios-app:
    name: iOS App Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "YourAppName.xcworkspace" # Wenn Sie ein Workspace verwenden
        XCODE_PROJECT: "YourAppName.xcodeproj" # Wenn Sie ein einfaches Xcode-Projekt verwenden
        XCODE_SCHEME: "YourAppName" # Ihr Build-Scheme
        IOS_SIGNING_CERTIFICATE: Encrypted(...) # Ihr verschlüsseltes Zertifikat
        IOS_PROVISIONING_PROFILE: Encrypted(...) # Ihr verschlüsseltes Provisioning Profile
        APP_STORE_CONNECT_API_KEY: Encrypted(...) # Optional, für automatische Veröffentlichung
      groups:
        - apple_credentials
        - signing_files
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: bundle install
      - name: Install CocoaPods Dependencies
        script: pod install
      - name: Build
        script: xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=YES CODE_SIGN_IDENTITY="iPhone Developer" PROVISIONING_PROFILE="$IOS_PROVISIONING_PROFILE"
      - name: Export .ipa
        script: xcodebuild -exportArchive -archivePath build/archive.xcarchive -exportOptionsPlist ./exportOptions.plist -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa
      - logs

    publishing:
      scripts:
        - name: Deploy to App Store
          script: |
            app_store_connect_api_key_file="app_store_connect_api_key.json"
            echo "$APP_STORE_CONNECT_API_KEY" | base64 --decode > $app_store_connect_api_key_file
            app_store_connect_publish \
              --api-key $app_store_connect_api_key_file \
              --ipa-path "build/ipa/*.ipa" \
              --skip-waiting-for-processing true
